openapi: 3.0.0
info:
  title: DIGIPIN API
  description: Encode and decode DIGIPIN based on latitude and longitude
  version: 1.0.0
servers:
  - url: http://localhost:5000/api

paths:
  /digipin/encode:
    post:
      summary: Encode lat/lon into DIGIPIN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                latitude:
                  type: number
                longitude:
                  type: number
      responses:
        '200':
          description: Successfully encoded DIGIPIN
          content:
            application/json:
              schema:
                type: object
                properties:
                  digipin:
                    type: string
        '400':
          description: Invalid input
    get:
      summary: Encode latitude and longitude into DIGIPIN
      parameters:
        - in: query
          name: latitude
          required: true
          schema:
            type: number
        - in: query
          name: longitude
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successfully encoded DIGIPIN
          content:
            application/json:
              schema:
                type: object
                properties:
                  digipin:
                    type: string
        '400':
          description: Invalid input

  /digipin/decode:
    post:
      summary: Decode DIGIPIN to coordinates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                digipin:
                  type: string
      responses:
        '200':
          description: Successfully decoded DIGIPIN
          content:
            application/json:
              schema:
                type: object
                properties:
                  latitude:
                    type: number
                  longitude:
                    type: number
        '400':
          description: Invalid DIGIPIN
    get:
      summary: Decode DIGIPIN to coordinates
      parameters:
        - in: query
          name: digipin
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully decoded DIGIPIN
          content:
            application/json:
              schema:
                type: object
                properties:
                  latitude:
                    type: number
                  longitude:
                    type: number
        '400':
          description: Invalid DIGIPIN

  /digipin/get-distance:
    post:
      summary: Calculate Surface distance between two DIGIPINs.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                src_digipin:
                  type: string
                dest_digipin:
                  type: string
      responses:
        '200':
          description: Successfully calculated Surface distance in Kilo-meters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  distance:
                    type: string
        '400':
          description: Invalid input
    get:
      summary: Calculate Surface distance between two DIGIPINs.
      parameters:
        - in: query
          name: src_digipin
          required: true
          schema:
            type: string
        - in: query
          name: dest_digipin
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Calculate Surface distance between two DIGIPINs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  distance:
                    type: string
        '400':
          description: Invalid input