services:
  digipin:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    volumes:
      - ../:/app
      - /app/node_modules
    command: npm run dev
